language: python
dist: bionic
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy3'
os:
  - linux
stages:
  - lint
  - test
env:
  - CELERY_VERSION=44
  - CELERY_VERSION=50
  - CELERY_VERSION=master
matrix:
  include:
    - python: '3.6'
      env: TOXENV=flake8
      stage: lint
  allow_failures:
    - env: CELERY_VERSION=master
before_install:
  # If TOXENV is not set, build it from the Python and Celery versions.
  - if [[ -v CELERY_VERSION ]]; then export TOXENV=${TRAVIS_PYTHON_VERSION}-celery${CELERY_VERSION}; fi; env
after_success:
  - |
          if [[ -v MATRIX_TOXENV ]]; then
              .tox/$TOXENV/bin/coverage xml
              .tox/$TOXENV/bin/codecov -e TOXENV
          fi;
install: pip install -U tox
script: tox -v
